// Wrapper.idl : IDL source for Wrapper
//

// This file will be processed by the MIDL tool to
// produce the type library (Wrapper.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(659455D2-E3D4-4F5B-86C8-CED36C5064AF),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IKeypad : IDispatch{
	[id(1)] HRESULT Open_USB();
};
[
	uuid(0473D872-B9F8-438A-841A-2260CCB9DC13),
	version(1.0),
]
library WrapperLib
{
	importlib("stdole2.tlb");
	[
		uuid(1578C775-3C7B-4822-B86E-9F45C18A5B3C)		
	]
	dispinterface _IKeypadEvents
	{
		properties:
		methods:
			[id(1)] HRESULT Callback(int data);
			[id(2)] HRESULT CB([in] int data);
	};
	[
		uuid(31E60A98-1BA1-4667-904B-8EC345F37917)		
	]
	coclass Keypad
	{
		[default] interface IKeypad;
		[default, source] dispinterface _IKeypadEvents;
	};
};

import "shobjidl.idl";
